# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Unified CICD for Website and API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test

      - name: Publish Web
        run: dotnet publish FinalProjDemo -c Release -o ${{env.DOTNET_ROOT}}/web

      - name: Upload artifact for Web deployment job
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: ${{env.DOTNET_ROOT}}/web

      - name: Publish API
        run: dotnet publish MyApi -c Release -o ${{env.DOTNET_ROOT}}/api

      - name: Upload artifact for API deployment job
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ${{env.DOTNET_ROOT}}/api


  deploy_web:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: web

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FinalProjDemo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_21D504E43C2D4219BFECD23A88949BB9 }}
          package: .

  deploy_api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: api

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'finalprojapi'
          slot-name: 'production'
          publish-profile: ${{ secrets.API_PUBLISH_PROFILE }}
          package: .